### ISSUE TITLE
Vimeo has changed it's CSV formatting

### ISSUE THREAD

**Issue by madaphaqa** [latenitefilms/MarkerToolbox#30] opened 2024-03-27 13:38 UTC
Hi, i bought your software last month and everything was REALLY fine on the first project i used it on. My client used the Vimeo review page to add notes, i downloaded the .csv file, drag and dropped it in the fcp workflow extension and obtained a nice compound with all the markers, easy peasy. It was the first time in years that getting notes from a client was so streamlined and simple.

In the last week i started a new project, a 20 episodes television series and i decided that i was the right project to get the most out of Vimeo and your software. I have already exported several interviews to be cut by my producers, they already added the notes, but today, with my surprise, when i tried to import it in Marker Toolbox, i have only obtained a very short compound clip with no markers whatsoever.

I tried to uninstall and reinstall the application, using the stand alone version instead of the workflow extension, but nothing seems to work. The only way to get a working compound clip with markers is to copy the content of the .csv file and processing it as a text, but in this way everything that is written on the .csv file is written on the marker so it is really confusing and annoying.

I downloaded the csv from the project i already closed last month (the one where i used Marker Toolbox without problems) and it gives me the same problem, a really short compound with no markers. Next thing, i searched in my hard disks for a backup of the old notes downloaded last month and those files work like a charm.

I opened in Text Edit the new and the old version of the .csv downloaded from Vimeo and there's something different in the syntax of the file, in the new version the are a lot more quote characters, i copy/paste here two lines from the different files:

OLD ONE - February, 23 2024
"PNSS24 V2",25,01:53:22,"ProNails Italia","qui metti il Collage Nail art",--,"Friday, February 23, 2024 At 3:41 PM",Yes

NEW ONE - Today March, 27 2024
"PNSS24 V2",25,01:53:22,"ProNails Italia","qui metti il Collage Nail art","""--""","""Friday, February 23"""", 2024 At 3:41 PM""",Yes

It seems a problem on the Vimeo side, but it renders almost unusable your application, i'm attaching the two files so you can check the situation and maybe give me a solution.

[review_notes_915781192.csv]
(https://github.com/latenitefilms/MarkerToolbox/files/14774062/review_notes_915781192.csv)

[OLD review_notes_915781192.csv](https://github.com/latenitefilms/MarkerToolbox/files/14774064/OLD.review_notes_915781192.csv)

Thank you very much,
Dave

**Comment by latenitefilms** [comment] 2024-03-28 20:43
Amazing! Thanks so much for the detailed bug report! I'll try and fix and push out a TestFlight build after the Easter long weekend (unfortunately I'm away from my computer the next few days).

**Comment by latenitefilms** [comment] 2024-04-02 05:58
To be honest, I'm not sure if this is a bug in Vimeo's CSV output, or if Marker Toolbox is incorrectly processing the incoming CSV file. I've reached out to them (ticket 2454966) - so hopefully they get back to me soon.

In the meantime, you could just open the CSV file in a text editor (I use BBEdit), and do a find and replace to remove the unnecessary quotes (i.e. replace `""""` with nothing, then replace `"""` with `"`)?

**Comment by latenitefilms** [comment] 2024-04-02 06:23
The problem definitely seems to be that Vimeo is outputting the CSV file incorrectly.

We're expecting the replies to be `--`, whereas the CSV is actually outputting `"--"` (i.e. wrapping the `--` within quotes).

If you do a find a replace to replace `"""--"""` with `"--"` - that should fix the issue.

Vimeo have already responded with an initial response - so we'll see if they concur that it's a bug or not.

**Comment by madaphaqa** [comment] 2024-04-02 09:59
Ok, it's a bit tricky but with a find and replace, everything works.
I hope that they fix the situation soon.
Ciao!

**Comment by latenitefilms** [comment] 2024-04-09 23:18
Vimeo has confirmed:

> After checking with Engineering, they let me know that this is indeed an intentional change designed for further security.

**Comment by latenitefilms** [comment] 2024-04-24 07:16
This has been fixed in Marker Toolbox v1.3.1. Thanks for reporting!

**Closed by latenitefilms** 2024-04-24 07:16 UTC
Labels: bug

**Comment by madaphaqa** [comment] 2024-04-24 07:40
Thank you for the fix!
